### PR TITLE
Allow redefining unrecognizedmacro

### PR DESCRIPTION
**Pull request by dalcde**

### CODE REVIEW

**Comment by PatrickMassot** [comment]
I don't understand that PR. Could you give a full TeX document showing the issue this is fixing. The snippet in the test doesn't compile in LaTeX.

**Comment by dalcde** [comment]
I fixed the test to now compile with latex (when wrapped in the usual
document boilerplate). After #190 is merged, I can use the
compare_output function to programmatically ensure the snippet indeed
works with tex as claimed.

**Comment by PatrickMassot** [comment]
Now that #190 is merged, could you update the test?

**Comment by dalcde** [comment]
Done

**Pull request merged**
