### PR TITLE
Specify python3 explicitly

### PR DESCRIPTION
**Pull request by dalcde**
We no longer support python2

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Do you understand the purpose of all those lines? Almost of these files are not meant to be executed but only imported. Why not removing those lines entirely?

**Comment by dalcde** [comment]
I agree. I merely did a sed -i **/*.py; easier than handpicking lines to
remove. Would you like me to remove the lines as well?

**Comment by PatrickMassot** [comment]
If you have the patience (or want to play with scripting) then yes.

**Comment by PatrickMassot** [comment]
Thanks!

**Pull request merged**
