### PR TITLE
Restore all tests by removing harmful unittests/__init__.py

### PR DESCRIPTION
**Pull request by PatrickMassot**
This reverts 10f51da083851247954aaabc0ad8d540e763c290 from @niklasp which introduced ``unittests/__init__.py``, which messed up imports in tests, which were then marked for skipping.

### CODE REVIEW

**Comment by niklasp** [comment]
How are you running your tests? I have the same problems like travis above. And it is connected to import problems of the "packages".

The command travis uses and I think that we should go with is:
```
pytest -v --cov-report= --cov=plasTeX
```

**Comment by PatrickMassot** [comment]
This is extremely mysterious (as often with python imports unfortunately). I added a couple of lines to requirements.txt and I can now type:
```bash
mkvirtualenv --python=/usr/bin/python3.6 plastex3.6
pip install -r requirements.txt
pip install .
pytest -v --cov-report= --cov=plasTeX
```
and all tests pass (except for Longtables tests that are skipped). The only weird thing is the warning: "Coverage.py warning: No data was collected. (no-data-collected)"
This is using python3.6.1 instead of 3.6.3 but I would be surprised if this is relevant.

**Comment by niklasp** [comment]
https://travis-ci.org/tiarno/plastex/builds/288518055?utm_source=github_status&utm_medium=notification says that also 
```
unittests/FunctionalPackageResource.py::test_package_resource FAILED
```
as well as
```
unittests/Packages/Alltt.py::Alltt::testCommands FAILED
unittests/Packages/Alltt.py::Alltt::testSimple FAILED
```
I have the exact same test output on my local computer. And I guess it is very related to the plastex warning
```
WARNING: unrecognized command/environment: longtable
```
I am getting, but I do not know how to fix it.

**Comment by niklasp** [comment]
Cool. How about longtables tests?

**Comment by PatrickMassot** [comment]
Ahah! I found it. This is what CI is meant to do: hunt down local installation specificities which hide bugs.
My system has dvipng installed. Without it, plasTeX falls back to using ``plasTeX/Imagers/dvi2bitmap.py`` and its wrong [Line 13](https://github.com/tiarno/plastex/blob/fc405f9218e54309a75d21cd7dae3ee8172045d6/plasTeX/Imagers/dvi2bitmap.py#L13).

Let me see if I can fix that.

**Comment by PatrickMassot** [comment]
Hum. I may have fixed dvi2bitmap but, without a proper imager available, the Alltt test fail. This is of course coming from the more global problem of the plastex CLI doing too much (tests in Alltt fail when calling the cli, not when using plastex as a lib). Right now I have to go somewhere else but I hope to come back to plasTeX in the evening. Feel free to try to fix that. I should be possible to run plasTeX without any available imager.

**Comment by niklasp** [comment]
I have the problem of imports always. The package should also work without having to modify the `PYTHON_PATH` or any other ENV variables. That is why probably I was adding `unittests/__init__.py`

**Comment by PatrickMassot** [comment]
Ok, that's enough for tonight. Now Travis is fine with alltt tests. I had to get rid of using the cli tool (after fighting with the way temp files are handled by Travis). Tomorrow I'll do long tables (I started but need some refactoring).

Interesting point: the old test had a typo ``\document{article}`` instead of ``\documentclass{article}``. Not sure what was tested here...

@niklasp could you please clone this version and try to test locally?

**Comment by PatrickMassot** [comment]
I forgot: I don't "modify the PYTHON_PATH or any other ENV variables" anywhere in all this quest.

**Comment by PatrickMassot** [comment]
Ok, I'm done with this PR. I can now run all tests on my computer and on Travis (except those discussed in #70 and #71 where I'm waiting for @kesmit13 comments).

I turned Alltt and Longtable into pytest style and removed all popen uses from these tests and it now works in Travis.

@niklasp can you confirm this is ok for you as well?

**Comment by niklasp** [comment]
unfortunately tests are failing locally :( even I see that they succeed on travis. I am getting the following errors at  c12d125
```
___________________________________________ test_simple ___________________________________________

tmpdir = local('/private/var/folders/8m/09t8bnl57r18s4wc7zsprvrh0000gn/T/pytest-of-n/pytest-79/test_simple0')

    def test_simple(tmpdir):
        text = '''\\begin{alltt}\n   line 1\n   line 2\n   line 3\n\\end{alltt}'''
        lines = ['', '   line 1', '   line 2', '   line 3', '']

        # Test text content of node
        doc = runDocument(text)
        out = doc.getElementsByTagName('alltt')[0]

        plines = out.textContent.split('\n')
>       assert lines == plines, 'Content doesn\'t match - %s - %s' % (lines, plines)
E       AssertionError: Content doesn't match - ['', '   line 1', '   line 2', '   line 3', ''] - ['']
E       assert ['', '   line...  line 3', ''] == ['']
E         Left contains more items, first extra item: '   line 1'
E         Use -v to get the full diff

/Users/n/Sites/plaste-massot/unittests/Packages/Alltt.py:71: AssertionError
__________________________________________ test_commands __________________________________________

tmpdir = local('/private/var/folders/8m/09t8bnl57r18s4wc7zsprvrh0000gn/T/pytest-of-n/pytest-79/test_commands0')

    def test_commands(tmpdir):
        text = '''\\begin{alltt}\n   line 1\n   \\textbf{line} 2\n   \\textit{line 3}\n\\end{alltt}'''
        lines = ['', '   line 1', '   line 2', '   line 3', '']

        # Test text content of node
        doc = runDocument(text)
        out = doc.getElementsByTagName('alltt')[0]

        plines = out.textContent.split('\n')
>       assert lines == plines, 'Content doesn\'t match - %s - %s' % (lines, plines)
E       AssertionError: Content doesn't match - ['', '   line 1', '   line 2', '   line 3', ''] - ['']
E       assert ['', '   line...  line 3', ''] == ['']
E         Left contains more items, first extra item: '   line 1'
E         Use -v to get the full diff

/Users/n/Sites/plaste-massot/unittests/Packages/Alltt.py:88: AssertionError
________________________________________ test_numberwithin ________________________________________

    def test_numberwithin():
        s = TeX()
        s.input(DOC)
        output = s.parse()
        equations =output.getElementsByTagName('equation')
>       assert equations[0].ref.textContent == '1.1'
E       AssertionError: assert '1' == '1.1'
E         - 1
E         + 1.1

/Users/n/Sites/plaste-massot/unittests/Packages/Amsmath.py:28: AssertionError
========================= 3 failed, 170 passed, 5 skipped in 1.90 seconds =========================
```

I ran the following steps to reproduce?
```
git clone https://github.com/PatrickMassot/plastex.git pm-plastex
cd pm-plastex
git checkout python3
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
pip install .
#mv unittest/Numbers.py unittest/test_numbers.py (there was a problem with jinja2 complaining about that name)
pytest -v
```

**Comment by PatrickMassot** [comment]
This is so weird. I can type all commands you provided, and apart from a strange warning when pip installing, everything goes smoothly (I usually use virtualenvwrapper to build virtual envs, but it shouldn't matter). What kind of OS are you using? Which version of python? I'm afraid there is not much I can do to help you. 

Next, I'll try to setup tox to test against different versions of python, this may reveal new issues.

**Comment by PatrickMassot** [comment]
Well, my computer and Travis now run tests against python 3.3, 3.4, 3.5 and 3.6 and still can't see any problem. 

@niklasp can you try to emulate the tests that fail by manually using plasTeX againt regular tex files?

**Comment by niklasp** [comment]
i am on osx. tested two machines with different pythons (3.5 and 3.6) and it fails both times. Try to hunt that bug down, yet its hard to find. Already spent some time there.

**Comment by PatrickMassot** [comment]
What about trying without pytest? What happens for instance if you create a file test.tex containing:
```latex
\documentclass{article}
\usepackage{amsmath}
\numberwithin{equation}{section}
\begin{document}
\section{First section}
\begin{equation}
a = b
\end{equation}
\section{Second section}
\begin{equation}
c = d
\end{equation}
\subsection{Subsection}
\begin{equation}
e = f
\end{equation}
\end{document}
```
and run ``plastex test.tex``. Do you see the correct numbering 1.1 or the incorrect 1 than seems to be seen by pytest on your machine?

**Comment by niklasp** [comment]
@PatrickMassot thanks for your effort first. Second: only the tests fail that use the "python as a library aproach" like in [Longtable.py#L29-32](https://github.com/tiarno/plastex/blob/python3/unittests/Packages/Longtable.py#L29-L32). It seems to be some os.related error, where plastex cannot find Packages (same error on all external + custom package tests). I am getting e.g. the error messages below, when I test the tex above
```
WARNING: unrecognized command/environment: thesection
WARNING: unrecognized command/environment: sectionname
WARNING: unrecognized command/environment: thesubsection
WARNING: unrecognized command/environment: subsectionname
```
Looking at the generated index.html shows the correct sectioning, when running with
[Longtable.py#L52](https://github.com/tiarno/plastex/blob/python3/unittests/Packages/Longtable.py#L52)
There might be some hidden os specific code somewhere, but investigating did not get me anywhere, I was always thinking that I was using the `TeX.parse` commands in the wrong way. But as it turns out it works on other machines. (I once thought it was related to the `.paux` files, but then, after hours I stopped investigating)

So what could I do? I guess I could either rewrite tests to have an os switch, i.e. some skip instructions for certain tests when on OSX, that would be a hack, but it is quite obligatory for me to see tests succeed, when developing. Even better would be a `test_tex_conversion` method with a clear interface like `test_tex_conversion ( tex_input ) : plasTeX.DOM.Document` that we could both use, and where you would go for the "default" way of
```
s = TeX()
s.input(tex_input)
return TeX.parse()
```
and I would have to write an own implementation that mimics the returned TeX Dom. Sounds like work... :| other ideas?

**Comment by PatrickMassot** [comment]
I'm a bit confused by your answer, especially since it contains links to the upstream version which are incompatible with the current state of this PR, and refer to test code instead of normal usage of plasTeX. I was refering to [this comment](https://github.com/tiarno/plastex/pull/102#issuecomment-337220710), specifically the test_numberwithin failure. 

What happens if you clone my python3 branch in a fresh virtual env, create in a file test.tex containaing:
```latex

\documentclass{article}
\usepackage{amsmath}
\numberwithin{equation}{section}
\begin{document}
\section{First section}
\begin{equation}
a = b
\end{equation}
\section{Second section}
\begin{equation}
c = d
\end{equation}
\subsection{Subsection}
\begin{equation}
e = f
\end{equation}
\end{document}
```
and run ``plastex test.tex``? Do you see errors then? How is the first equation numbered?

**Pull request closed without merging**
