### PR TITLE
Backport some fixes from gerby-project

### PR DESCRIPTION
**Pull request by dalcde**
The first commit fixes spacing issues when the theorem content only has one paragraph.

The second commit marks `proof` as `blockType`.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
I guess there is no problem, but let's ping @chngr and @pbelmans to make sure they are happy you are helping with #160.

It would be nice to have a test clearly demonstrating what is fixed.

**Comment by pbelmans** [comment]
Yes, I would be more than happy to help, and thanks for the amazing work you've already done! I've been following the developments a bit, but I haven't had time yet to actually contribute.

**Comment by dalcde** [comment]
On Thu, Apr 16, 2020 at 02:18:46AM -0700, Patrick Massot wrote:
>I guess there is no problem, but let's ping @chngr and @pbelmans to make sure they are happy you are helping with #160.

At the moment I'm merely backporting changes that I personally use. I
can potentially help with #160 but it is not the intention of the
current PR. I try my best to cherry-pick commits from gerby-project to
give the right people credit, but sometimes it is difficult.

>It would be nice to have a test clearly demonstrating what is fixed.

I'm not quite sure what tests I can write.

For the first one, the theorem environment puts the content of the
theorem in a paragraph (<p> tag in html) iff there is more than one
paragraph. This leads to inconsistent spacing, because <p></p> generally
puts some surrounding spaces.

For the second one, a blockType environment automatically ends previous
paragraphs if present. Currently, if we have
```tex
a
\begin{proof}
b
\end{proof}
c
```
we end up with
```html
<p>a <div class="proof_wrapper"> ... </div> c</p>
```
By making `proof` blockType, we would instead have
```html
<p>a</p> <div class="proof_wrapper"> ... </div> <p>c</p>
```
Technically, the former is invalid html, since paragraphs cannot
supposed to include "block" elements. However, most html parsers are
pretty lenient and parses this without much issues (albeit possibly with
weird spacing).

In general, the issue with these is that they produce slightly less
optimal html (and presumably for other renderers too). This would be
difficult to test short of asking for a specific generated html/parsed
tree, which would be pretty fragile (I learnt my lesson with the tikz
stuff)

**Comment by dalcde** [comment]
>I guess there is no problem, but let's ping @chngr and @pbelmans to make sure they are happy you are helping with #160.

At the moment I'm merely backporting changes that I personally use. I
can potentially help with #160 but it is not the intention of the
current PR. I try my best to cherry-pick commits from gerby-project to
give the right people credit, but sometimes it is difficult.

>It would be nice to have a test clearly demonstrating what is fixed.

I'm not quite sure what tests I can write.

For the first one, the theorem environment puts the content of the
theorem in a paragraph (<p> tag in html) iff there is more than one
paragraph. This leads to inconsistent spacing, because <p></p> generally
puts some surrounding spaces.

For the second one, a blockType environment automatically ends previous
paragraphs if present. Currently, if we have
```tex
a
\begin{proof}
b
\end{proof}
c
```
we end up with
```html
<p>a <div class="proof_wrapper"> ... </div> c</p>
```
By making `proof` blockType, we would instead have
```html
<p>a</p> <div class="proof_wrapper"> ... </div> <p>c</p>
```
Technically, the former is invalid html, since paragraphs cannot
supposed to include "block" elements. However, most html parsers are
pretty lenient and parses this without much issues (albeit possibly with
weird spacing).

In general, the issue with these is that they produce slightly less
optimal html (and presumably for other renderers too). This would be
difficult to test short of asking for a specific generated html/parsed
tree, which would be pretty fragile (I learnt my lesson with the tikz
stuff)

**Comment by pbelmans** [comment]
> I try my best to cherry-pick commits from gerby-project to give the right people credit, but sometimes it is difficult.

Don't worry about cherry-picking commits from Gerby from me!

**Comment by chngr** [comment]
This looks great! Glad some of our work is helpful to plasTeX! Feel free to cherry pick commits from myself, as well!

**Comment by PatrickMassot** [comment]
Ok, I tried to write tests. First please add a file `unittests/theorem.py` containing:
```python
from plasTeX.TeX import TeX
from plasTeX.Base.TeX.Primitives import par

def test_single_paragraph_theorem():
    """Check single paragraph theorem does contain a paragraph"""
    tex = TeX()
    tex.input(r'''
      \newtheorem{thm}{Theorem}
      \begin{thm}
      $1+1=2$
      \end{thm}
      ''')
    nodes = tex.parse().getElementsByTagName('thm')[0].childNodes
    assert len(nodes) == 1
    assert isinstance(nodes[0], par)
```
That one works nicely. It fails before your patch, and works after.

For proofs I haven't been able to observe a fix. I tried adding `unittests/proof.py` containing:
```python
from plasTeX.TeX import TeX
from plasTeX.Base.TeX.Primitives import par

def test_proof_in_par():
    """Check proof environment ends the current paragraph."""
    tex = TeX()
    tex.input(r'''
      \documentclass{article}
      \begin{document}

      a
      \begin{proof}
      b
      \end{proof}
      c

      \end{document}
      ''')
    doc = tex.parse()
    proof = doc.getElementsByTagName('proof')[0]
    assert not isinstance(proof.parentNode, par)

def test_proof_dont_create_par():
    """Check proof environment don't end up inside a paragraph"""
    tex = TeX()
    tex.input(r'''
      \documentclass{article}
      \begin{document}

      a

      \begin{proof}
      b
      \end{proof}

      c

      \end{document}
      ''')
    doc = tex.parse()
    proof = doc.getElementsByTagName('proof')[0]
    assert not isinstance(proof.parentNode, par)
```
Which fail, but your patch doesn't seem to fix it. Did I misunderstand the issue? (tests also helps communicating *what* is the issue you want to fix).

Is it clearer what I mean by test? Do you know you can [ask pytest to run only selected tests](https://docs.pytest.org/en/latest/usage.html#specifying-tests-selecting-tests)?  For instance here try `pytest -k proof`. Or better, `pytest -k proof --pdb` to drop into pdb when the assertion fails (after installing [pdbpp](https://github.com/pdbpp/pdbpp) of course).

**Comment by dalcde** [comment]
I've added the tests. `plasTeX` puts *everything* inside `par` environments. However, blockType objects are put in their own `par` instance, and the `par` instance is marked `blockType`. The HTML5 renderer checks if the `par` instance is `blockType`, and if its, it omits the `<p></p>` tags.

**Comment by PatrickMassot** [comment]
Great! Tests make everything much clearer, now and in the distant future.

**Pull request merged**
