### PR TITLE
Fix sorting of index entries

### PR DESCRIPTION
**Pull request by ugoertz**
This is a follow-up to issue #232 which fixed one problem with indexing, but left another one open, as I noticed later. See the new test which fails without the proposed change to DOM/__init__.py.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Thanks! Could you please use in the test a TeX source that pdflatex + makeindex can actually use, so that we can compare? (We don't have to put the comparison in the test, but I'd like to see it before merging).

**Comment by PatrickMassot** [comment]
I'm sorry about CI integration complaining about things unrelated to your PR. You can rebase on master to fix that.

**Comment by ugoertz** [comment]
Thanks, yes that makes sense. I expanded the TeX so that it can be used with pdflatex/makeindex.

**Comment by PatrickMassot** [comment]
Thanks!

**Pull request merged**
