### PR TITLE
Copy xymatrix implementation from gerby.

### PR DESCRIPTION
**Pull request by dalcde**
I have not verified the implementation but added tests to check that
source returns the right result.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
In the PR title, do you mean Gerby instead of plasTeX?

**Comment by dalcde** [comment]
Yes...

**Comment by PatrickMassot** [comment]
Do you know if Gerby would work if you used the verbatim environment you used for TikZ? Otherwise I'm fine merging without really understanding what Gerby does with this. We don't want to spend too much time on this super-deprecated package.

**Comment by pbelmans** [comment]
I agree `xy` is super-deprecated, but given how important it is for the Stacks project and Kerodon, it is unfortunately important.

I don't know how the implementation you refer to works, but XyJax needs the raw TeX code, maybe with macros expanded, whatever I did in Gerby is trying to do exactly this, if I remember correctly (but it's been 3 years or so that I've done this).

**Comment by PatrickMassot** [comment]
@pbelmans it would be really really helpful if you give us things to test here.

**Comment by dalcde** [comment]
On Sat, Apr 25, 2020 at 08:53:26AM -0700, Patrick Massot wrote:
>Do you know if Gerby would work if you used the verbatim environment you used for TikZ? Otherwise I'm fine merging without really understanding what Gerby does with this. We don't want to spend too much time on this super-deprecated package.

This doesn't quite work because you usually invoke \xymatrix inside
math mode, so it is hard to automatically deploy the imager in this
case. If we just put everything in verbatim without using the imager,
there would be no macro expansions at all, which would break a lot of
things (e.g. if we defined \R to \mathbb{R}, we don't want \R to show
up).

As Pieter said, the goal of this package is to make sure running
`obj.source` returns a source that mathjax understands. This generally
involves macro expanding all user-defined macros but not "built in" xy
matrix macros. This largely involves listing out all xy matrix macros to
prevent plasTeX from doing anything with it (and sometimes control the
spacing precisely), but there is not much programmatic things to do.

**Comment by PatrickMassot** [comment]
Ok, this is what I imagined. Since this seems good enough for Gerby let's move on (and hope people will stop using that zombie thing really soon).

**Pull request merged**
