### PR TITLE
fix sort in natbib

### PR DESCRIPTION
**Pull request by efiminem**
Previously, a sorting function in natbib was not working because it requires a sorting key instead of comparator.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Thanks for this contribution. As I explained in https://github.com/plastex/plastex/issues/234#issuecomment-750855428, it would be much nicer to also have a test showing this function does what it is expected to do. And I still have no idea what it is expected to do (and still no idea why people are using natbib in 2021).

**Comment by efiminem** [comment]
Thanks for the answer. I see that you've basically suggested the same fix, haven't noticed it because the issue was closed. I was not diving into details of how the function works, but this particular line of code is obviously not compatible with the newer python and should be fixed (regardless of the purpose of the code). Investigating the package further could be a part of another request. As of using natbib in 2021 - well, sometimes you just have a legacy code.

**Comment by PatrickMassot** [comment]
I don't particularly enjoy being the grumpy old man reluctant to merge code that is obviously an improvement. The point is the original code was written probably more than 15 years ago and nobody took the trouble to write a test at that time. I guess that code was "obviously" correct at this time. Then python3 came and that code broke, and nobody noticed because there was no test (and no natbib user). Fixing this today without writing a test is simply setting up a trap for our successor 15 years away from now.

**Comment by efiminem** [comment]
Ok, I've looked into the code more closely. This function is called when sort option of natbib is used and citations are numbers. Its purpose is to sort the citations which go in one place (e.g. [3, 7, 8, 2] should be changed to [2, 3, 7, 8]). So, in order to see any difference due to this implementation an example should contain such one-place citations.

Note, that due to bad implementation the sorting was also called when list of one-place citations is empty or contained only one element. This is the reason why example provided in #263 was also triggering the sorting despite consisting only of one reference. In addition to converting the method to newer python I've also added two changes:

1.  Now the length of one-place citations is checked and sorting is performed when it contains at least 2 elements.
2. `bibpunct.punctuation['style'] in 'ns'` is changed to `self.isNumeric()` to make it more clear what this part of the code do.

I've also noticed another related problem while following the code. In some places `self.bibitems` was unnecessary called resulting in additional sorting for each already sorted item. I've fixed it in another commit.

As for the tests, I'm not sure what is the best place to put them. Is it `unittests/Packages/sources/`? The simple example which uses the sorting functionality is attached: [sorting.zip](https://github.com/plastex/plastex/files/6759053/sorting.zip).

**Comment by PatrickMassot** [comment]
Sorry about the delay. `unittests/Packages/sources/` would be the place to put a tex file if you want to do a functional end-to-end test, from the tex file to the rendered html. This is not the relevant level here. We want tests testing that sorting option, not the renderer. I started to write tests but I realized this package is written in a way that does not allow handling several files without re-initializing everything. There is a global variable `PackageOptions` which stores the configuration and, much worse, the global class `bibpunct` is modified when reading the options. So writing a series of tests with various options for `natbib` is currently very complicated (tests would have weird interactions with each other). So I will merge this PR, and hope I'll find courage to sanitize this package and write a couple of tests.

**Comment by PatrickMassot** [comment]
@efiminem if you are curious, you can have a look at 4ce3bae0871dd47084050d7038991729e0c6bde3 and fd5ef4270dc3da8be15917204c5eb6257424f6a9.

**Pull request merged**
