### PR TITLE
README: add sections on installation, basic usage and how to contribute.

### PR DESCRIPTION
**Pull request by grunweg**
Hi! I just looked at plastex in detail; thanks a lot for this project!
I found getting to grips with it slightly difficult; part is that I didn't find the docs (which are helpful!) until later. I gather this is a [known problem](https://github.com/plastex/plastex/issues/164). Find below some improvements to the README which would have helped me.

Notes.
- The link `https://plastex.github.io/plastex/#users` doesn't exist yet (but doesn't go stale either).
- I would find a section "contributing" helpful (see below). What to put there depends on you :-) I've put some questions/possible options. *Please* let me know if any of these is correct/what else would be accurate.

### CODE REVIEW

**Comment by grunweg** [comment]
**Why am I making these changes? Where am I coming from?**
*Consider this a mix of various bits of feedback with a rationale for my changes. Skip this if you wish.*

1. How to install: I came here via the [sphere eversion blueprint](https://github.com/leanprover-community/sphere-eversion) whose readme recommends cloning this github repository. That seemed unusual to me (I'm more used to a simple `pip install packagename`), hence I was wondering if the package was also on PyPI (or why not)... Turns out it was, but mentioning that would answer this question :-)

2. plasTeX options
After installation, plasTeX compiled the sample document fine, but I wanted to merge all files in one. The webpage said this was possible - but I didn't see any hints how. The README doesn't have it, so I looked at the `plastex --help` output and went from there. I only saw the [documentation](https://plastex.github.io/plastex/plastex/plastex.pdf) the next day. Linking that more prominently would have helped a lot

3. The github page was not helping me find the documentation. I opened a separate issue about this.

4. The tutorial is very hard to discover. I only found out about this by browsing the github issues.
In my opinion, that's a rather high bar. Linking it more prominently would reduce that.
If the tutorial is somewhat outdated, I'd rather link the outdated ressource than none.
(In my case, figuring out how to extend plasTeX to match my need would be *much* harder without any tutorial. Knowing the high-level structure of things certainly seems very helpful for this. This matches [other recommendations I've seen](https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html))

Relatedly, the post above would even recommend an ARCHITECTURE file in the repository.
If that's a widely followed convention (I don't know), even including a dummy file (with a mere "refer to [this tutorial](link here) for details) would help. Otherwise, either seems equally good to me.

5. Perhaps I'm too used to open source projects that are very [actively](https://brson.github.io/2017/04/05/minimally-nice-maintainer#be-clear-about-what-you-expect) [maintained](https://manishearth.github.io/blog/2016/01/03/making-your-open-source-project-newcomer-friendly/): for me, seeing an explicit "contributions are welcome, this and that is the most useful to us" goes a long way to feel my efforts welcome. Even "this is a side project to all of us, we welcome your patches, but responding might take a while" sets clear expectations and helps.

If I feel contributions were not useful, I might move elsewhere, which seems a lose-lose situation. (I want to scratch an itch here!)

**My perspective/background** so you can calibrate my feedback accordingly: I'm mostly a simple user, but would like to tweak plasTeX in one particular way. I started looking at it yesterday, hence am still quite a beginner to plasTeX.

**Comment by grunweg** [comment]
**Update.** I see that the tutorial used to be mentioned on the main page. Hm. I'd rather link to an outdated tutorial than to none. Perhaps linking it on the README only could be a compromise?

**Comment by PatrickMassot** [comment]
Thank you very much for your contribution. I don't think it really improves the situation however. The idea of the current README is to simply redirect readers to the main webpage of the project which is all about documentation. I will edit this main webpage so that the link to the full documentation comes earlier (although it should definitely be read *after* the main webpage).

I don't understand what you refer to with ` https://plastex.github.io/plastex/#users`. Where did you see that link?

We already have information about contribution located in `CONTRIBUTING.md` which is the standard place to look at. After seeing that suggestion, I just added some information into that file. Thanks for the suggestion.

The tutorial you found is so outdated that nothing good can come of using it. I'll try to find how to remove it.

**Comment by PatrickMassot** [comment]
I should add that I also have a new work in progress tutorial somewhere that I should finish one day. Time is very scarce but I will try.

**Comment by grunweg** [comment]
Thanks for the quick response!
- CONTRIBUTING.md is indeed a much better place for these things. (I find the history remark really helpful.)
- FWIW, I originally didn't look for CONTRIBUTING.md because the README was so short and the webpage didn't mention it (I simply assumed it wasn't there). That's clearly a flawed heuristic --- pointing to it from the webpage addresses this well.
- About the tutorial: sure, makes sense. I'm looking forward to the new tutorial, at some point. (Though it seems *I* will not need it for the time being.)

**Comment by grunweg** [comment]
Actually, brief installation instructions would be useful. Suggested in #303.

**Pull request closed without merging**
