### PR TITLE
Remove non-existent \ifeven command

### PR DESCRIPTION
**Pull request by dalcde**

### CODE REVIEW

**Comment by PatrickMassot** [comment]
What would we gain from removing this?

**Comment by dalcde** [comment]
We get rid of code that is arguably wrong

**Comment by PatrickMassot** [comment]
What I don't understand is why this is "wrong". The test suggests it works.

**Comment by dalcde** [comment]
A TeX engine should not implement commands that do not exist in tex.

One possible (albeit unlikely) issue is that this prevents people from defining their own command called \ifeven.

**Comment by PatrickMassot** [comment]
I can't say I'm really convinced but I merged it since it seems important to you, and I hope nobody else cares.

**Pull request merged**
