### PR TITLE
Don't include empty properties in CSSStyles.inline

### LINKED ISSUE #223: CSSStyles.inline can produce empty properties
`obj.style.inline` can produce properties with empty values if the node for the value produces empty text.

For example, `\includegraphics[width=\textwidth]{image.png}` produces `style="width:"` in the `` tag in the HTML5 renderer.

### PR DESCRIPTION
**Pull request by christianp**
fixes #223

### CODE REVIEW

**Comment by PatrickMassot** [comment]
Could you please add a couple of unit tests (one showing the fix and one proving it still works when something should be written)?

**Comment by christianp** [comment]
I've added some tests. I hope I've followed your style of testing!

**Comment by PatrickMassot** [comment]
I'm sorry I missed this message in August. Thanks for adding the tests. The question about testing style unfortunately doesn't make any sense because plasTeX has several styles of testing. I'll reformat this to the current style.

**Comment by PatrickMassot** [comment]
FYI, the new style can be seen in 8648fa13150b0794b41b6573325cccf418a4ece3. Hopefully this diff makes it clear why we switched to pytest for new tests.

**Pull request merged**
